package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"unicode"

	"github.com/kitti12911/lib-util/v2/fieldmask"
)

type model struct {
	name      string
	table     string
	columns   map[string]string
	relations []relation
}

type relation struct {
	name  string
	model string
	child bool
}

type stringList []string

func (l *stringList) String() string {
	return strings.Join(*l, ",")
}

func (l *stringList) Set(value string) error {
	if value == "" {
		return fmt.Errorf("value is required")
	}
	*l = append(*l, value)
	return nil
}

func main() {
	var roots stringList

	modelDir := flag.String("model-dir", "internal/database", "directory containing Bun model files")
	outPath := flag.String("out", "gen/database/fieldmap_generated.go", "generated Go output path")
	packageName := flag.String("package", "database", "generated Go package name")
	flag.Var(&roots, "root", "root model type to generate field maps for; repeatable")
	flag.Parse()

	if len(roots) == 0 {
		panic("at least one -root is required")
	}

	models, err := parseModelDir(*modelDir)
	if err != nil {
		panic(err)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by fieldmapgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", *packageName)

	for _, rootName := range roots {
		root, ok := models[rootName]
		if !ok {
			panic(fmt.Sprintf("%s model not found", rootName))
		}

		maps := map[string]fieldMap{}
		visit(models, root, fieldmask.RootNestedName, maps, map[string]bool{})

		fmt.Fprintf(&buf, "const %sRootNestedName = %q\n\n", root.name, fieldmask.RootNestedName)
		writeMap(&buf, root.name+"RootFields", maps[fieldmask.RootNestedName].fields)

		nestedNames := make([]string, 0, len(maps))
		for nestedName := range maps {
			if nestedName == fieldmask.RootNestedName {
				continue
			}
			nestedNames = append(nestedNames, nestedName)
		}
		sort.Strings(nestedNames)

		for _, nestedName := range nestedNames {
			fieldMap := maps[nestedName]
			writeMap(&buf, fieldMap.modelName+"Fields", fieldMap.fields)
		}
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(*outPath, out, 0o644); err != nil {
		panic(err)
	}
}

type fieldMap struct {
	modelName string
	fields    map[string]string
}

func visit(models map[string]model, m model, nestedName string, maps map[string]fieldMap, seen map[string]bool) {
	if seen[m.name] {
		return
	}
	seen[m.name] = true

	maps[nestedName] = fieldMap{
		modelName: m.name,
		fields:    m.columns,
	}

	for _, rel := range m.relations {
		if !rel.child {
			continue
		}

		relModel, ok := models[rel.model]
		if !ok {
			continue
		}

		childName := snake(rel.name)
		if nestedName != fieldmask.RootNestedName {
			childName = nestedName + "." + childName
		}
		visit(models, relModel, childName, maps, seen)
	}
}

func parseModelDir(dir string) (map[string]model, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	models := make(map[string]model)
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}

		fileModels, err := parseModelFile(filepath.Join(dir, name))
		if err != nil {
			return nil, err
		}
		for name, model := range fileModels {
			models[name] = model
		}
	}

	return models, nil
}

func parseModelFile(path string) (map[string]model, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	models := make(map[string]model)
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}

		for _, spec := range gen.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			strct, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			m, ok := parseModel(typeSpec.Name.Name, strct)
			if ok {
				models[m.name] = m
			}
		}
	}

	return models, nil
}

func parseModel(name string, strct *ast.StructType) (model, bool) {
	m := model{
		name:    name,
		columns: make(map[string]string),
	}

	for _, field := range strct.Fields.List {
		tag := structTag(field)
		bunTag := tag.Get("bun")
		if bunTag == "" {
			continue
		}

		if len(field.Names) == 0 && strings.Contains(bunTag, "table:") {
			m.table = tagOptionValue(bunTag, "table")
			continue
		}

		if len(field.Names) == 0 {
			continue
		}

		fieldName := field.Names[0].Name
		if strings.Contains(bunTag, "rel:") {
			m.relations = append(m.relations, relation{
				name:  fieldName,
				model: modelTypeName(field.Type),
				child: isChildRelation(bunTag),
			})
			continue
		}

		column := strings.Split(bunTag, ",")[0]
		if column == "" {
			continue
		}
		m.columns[snake(fieldName)] = column
	}

	sort.Slice(m.relations, func(i, j int) bool {
		return m.relations[i].name < m.relations[j].name
	})

	return m, m.table != ""
}

func structTag(field *ast.Field) reflect.StructTag {
	if field.Tag == nil {
		return ""
	}
	return reflect.StructTag(strings.Trim(field.Tag.Value, "`"))
}

func tagOptionValue(tag string, key string) string {
	for _, opt := range strings.Split(tag, ",") {
		if value, ok := strings.CutPrefix(opt, key+":"); ok {
			return value
		}
	}
	return ""
}

func isChildRelation(tag string) bool {
	for _, opt := range strings.Split(tag, ",") {
		switch opt {
		case "rel:has-many", "rel:has-one":
			return true
		}
	}
	return false
}

func modelTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.StarExpr:
		return modelTypeName(t.X)
	case *ast.ArrayType:
		return modelTypeName(t.Elt)
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return t.Sel.Name
	default:
		return ""
	}
}

func writeMap(buf *bytes.Buffer, name string, fields map[string]string) {
	fmt.Fprintf(buf, "var %s = map[string]string{\n", name)
	keys := make([]string, 0, len(fields))
	for key := range fields {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(buf, "\t%q: %q,\n", key, fields[key])
	}
	buf.WriteString("}\n\n")
}

func snake(name string) string {
	var out []rune
	runes := []rune(name)
	for i, r := range runes {
		if i > 0 && shouldSplitWord(runes, i) {
			out = append(out, '_')
		}
		out = append(out, unicode.ToLower(r))
	}
	return string(out)
}

func shouldSplitWord(runes []rune, i int) bool {
	prev := runes[i-1]
	curr := runes[i]

	if unicode.IsLower(prev) && unicode.IsUpper(curr) {
		return true
	}
	if unicode.IsUpper(prev) && unicode.IsUpper(curr) && i+1 < len(runes) && unicode.IsLower(runes[i+1]) {
		return true
	}
	return false
}
